version: "3"

services:
  app:
    build:
      args:
        user: veselov
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: audiobook
    volumes:
      - ./conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
